const USER_ROLES = {
  ADMIN: "ADMIN",
  TEACHER: "TEACHER",
  STUDENT: "STUDENT"
};

const ASSIGNMENT_STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  CLOSED: "CLOSED"
};

const SUBMISSION_STATUS = {
  SUBMITTED: "SUBMITTED",
  CHECKED: "CHECKED",
  EVALUATED: "EVALUATED",
  REJECTED: "REJECTED"
};

const RISK_LEVEL = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH"
};

const NOTIFICATION_TYPES = {
  ASSIGNMENT_CREATED: "ASSIGNMENT_CREATED",
  SUBMISSION_CHECKED: "SUBMISSION_CHECKED",
  EVALUATION_DONE: "EVALUATION_DONE",
  GENERAL: "GENERAL"
};

const FILE_TYPES = {
  PDF: "pdf",
  DOCX: "docx",
  TXT: "txt"
};

const DEFAULT_ADMIN = {
  name: "Admin User",
  email: "admin@gmail.com",
  password: "Admin@123",
  role: USER_ROLES.ADMIN
};

module.exports = {
  USER_ROLES,
  ASSIGNMENT_STATUS,
  SUBMISSION_STATUS,
  RISK_LEVEL,
  NOTIFICATION_TYPES,
  FILE_TYPES,
  DEFAULT_ADMIN
};